BEGIN;
UPDATE public.companies SET razao_social = 'POSTO SAO ROQUE LTDA' WHERE cnpj = '00.641.761/0001-22' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'SOL COMERCIO DE COMBUSTIVEIS LTDA' WHERE cnpj = '01.330.605/0001-03' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'SAO BERNARDO SERVICOS AUTOMOTIVOS LTDA' WHERE cnpj = '01.427.744/0001-50' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'OLIVEIRA COMERCIO DE DERIVADOS DE PETROLEO LTDA' WHERE cnpj = '01.668.012/0001-51' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'ROTA 020 COMBUSTIVEIS LTDA' WHERE cnpj = '02.455.511/0001-23' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'AUTO POSTO SIDNEY LTDA' WHERE cnpj = '02.763.234/0001-16' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'POSTO DU FIGUEIREDO COMERCIO VAREJISTA DE COMBUSTIVEIS LTDA' WHERE cnpj = '03.394.756/0001-50' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'AUTO POSTO SOF NORTE LTDA' WHERE cnpj = '03.951.672/0001-70' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'STAMPALLE COMERCIO DE COMBUSTIVEIS LTDA' WHERE cnpj = '04.020.339/0001-00' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'BORGES DAHER COMERCIO DE DERIVADOS DE PETROLEO LTDA' WHERE cnpj = '04.187.151/0001-51' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'POSTO RODOTRUCK CASTILHO LTDA' WHERE cnpj = '06.229.055/0001-54' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'AUTO POSTO RODOTRUCK DE PRESIDENTE PRUDENTE LTDA' WHERE cnpj = '07.026.084/0001-81' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'SAO ROQUE REPRESENTACAO COMERCIAL DE COMBUSTIVEIS' WHERE cnpj = '09.136.223/0001-55' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'CM COMERCIO DE COMBUSTIVEIS LTDA' WHERE cnpj = '11.280.816/0001-32' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'ACL COMERCIO DE ALIMENTOS LTDA' WHERE cnpj = '12.810.963/0001-30' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'LIDER CONSULTORIA E REPRESENTACAO LTDA' WHERE cnpj = '18.194.813/0001-25' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'COMELLI COMERCIO DE COMBUSTIVEIS LTDA' WHERE cnpj = '18.768.803/0001-56' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'MTO PARTICIPACOES EMPRESARIAIS LTDA' WHERE cnpj = '22.061.566/0001-66' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'SAO ROQUE ADMINISTRADORA DE BENS PROPRIOS LTDA' WHERE cnpj = '22.160.682/0001-32' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'RODOTRUCK MANIA LOJA DE CONVENIENCIA LTDA' WHERE cnpj = '22.272.274/0001-72' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'CIM EMPREENDIMENTOS IMOBILIARIOS LTDA' WHERE cnpj = '22.309.617/0001-26' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'POSTO SAO ROQUE ALIANCA LTDA' WHERE cnpj = '23.049.249/0001-97' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'ALIANCA PARTICIPACOES S A' WHERE cnpj = '23.112.210/0001-77' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'APOIO SERVICOS ADMINISTRATIVOS LAGO SUL LTDA' WHERE cnpj = '25.249.058/0001-02' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'REI ALVIM COMERCIO DE ALIMENTOS LTDA' WHERE cnpj = '26.075.154/0001-36' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'LORD ALVIM COMERCIO DE ALIMENTOS LTDA' WHERE cnpj = '26.332.112/0001-33' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'IMPERADOR ALVIM COMERCIO DE ALIMENTOS LTDA' WHERE cnpj = '26.428.809/0001-02' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'SAO ROQUE MORRINHOS COMERCIO VAREJISTA DE COMBUSTIVEIS LTDA' WHERE cnpj = '26.609.432/0001-98' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'TRANSRODOTRUCK TRANSPORTES LTDA' WHERE cnpj = '27.233.325/0001-70' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'PRINCIPE ALVIM COMERCIO DE ALIMENTOS LTDA' WHERE cnpj = '28.428.268/0001-48' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'SR ESPLANADA COMERCIO VAREJISTA DE COMBUSTIVEIS LTDA' WHERE cnpj = '28.932.629/0001-99' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'GLADIADOR ALVIM COMERCIO DE ALIMENTOS LTDA' WHERE cnpj = '28.953.109/0001-62' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'CONDE ALVIM COMERCIO DE ALIMENTOS LTDA' WHERE cnpj = '28.993.561/0001-58' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'DUQUE ALVIM COMERCIO DE ALIMENTOS LTDA' WHERE cnpj = '29.087.671/0001-13' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'POSTO DU FIGUEIREDO II LTDA' WHERE cnpj = '29.483.998/0001-04' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'SR SAO PAULO COMERCIO VAREJISTA DE COMBUSTIVEIS LTDA' WHERE cnpj = '29.907.570/0001-41' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'POSTO SAO ROQUE CERRADAO LTDA' WHERE cnpj = '31.160.539/0001-31' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'POSTO VEREDA VERDE LTDA' WHERE cnpj = '31.912.144/0001-48' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'SR TRANSPORTADORA E LOCADORA DE CAMINHOES S.A - DF' WHERE cnpj = '32.087.259/0001-08' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'PEROLA DO ATLANTICO EMPREENDIMENTOS IMOBILIARIOS LTDA' WHERE cnpj = '33.086.557/0001-46' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'BARAO ALVIM COMERCIO DE ALIMENTOS LTDA' WHERE cnpj = '34.840.241/0001-60' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'REGENTE ALVIM COMERCIO DE ALIMENTOS LTDA' WHERE cnpj = '35.238.002/0001-06' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'ESCUDEIRO ALVIM COMERCIO DE ALIMENTOS LTDA' WHERE cnpj = '35.252.660/0001-44' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'ARQUIDUQUE ALVIM COMERCIO DE ALIMENTOS LTDA' WHERE cnpj = '35.254.858/0001-67' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'SENHOR ALVIM COMERCIO DE ALIMENTOS LTDA' WHERE cnpj = '35.257.416/0001-74' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'POSTO SAO ROQUE SIMOLANDIA LTDA' WHERE cnpj = '35.257.918/0001-03' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'POSTO SAO ROQUE ALVORADA LTDA' WHERE cnpj = '35.273.451/0001-87' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'VISCONDE ALVIM COMERCIO DE ALIMENTOS LTDA' WHERE cnpj = '35.359.111/0001-73' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'CAVALEIRO ALVIM COMERCIO DE ALIMENTOS LTDA' WHERE cnpj = '35.378.393/0001-56' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'MG COMERCIO DE COMBUSTIVEIS LTDA' WHERE cnpj = '36.203.543/0001-53' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'ALVIM INVESTIMENTOS E GESTAO EMPRESARIAL LTDA' WHERE cnpj = '36.427.450/0001-02' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'SANTA MARIA DERIVADOS DE PETROLEO LTDA' WHERE cnpj = '37.639.036/0001-20' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'SONHO VERDE COMBUSTIVEIS LTDA' WHERE cnpj = '38.251.020/0001-08' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'CONSORTE PARTICIPACOES S.A' WHERE cnpj = '39.247.957/0001-72' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'FORTEM PARTICIPACOES S.A' WHERE cnpj = '39.251.221/0001-78' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'MAGNA PARTICIPACOES S.A' WHERE cnpj = '39.274.122/0001-01' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'QUATTRO PARTICIPACOES S.A' WHERE cnpj = '39.275.594/0001-89' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'ORNELAS PARTICIPACOES EMPRESARIAIS LTDA' WHERE cnpj = '39.324.417/0001-45' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'SUPORTE SERVICOS ADMINISTRATIVOS LAGO SUL LTDA' WHERE cnpj = '40.082.322/0001-41' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'AQUILA HOLDING S.A' WHERE cnpj = '40.237.633/0001-32' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'KASTRO HOLDING S.A' WHERE cnpj = '40.238.371/0001-20' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'AUTO POSTO PRO TORK RIO PRETO LTDA' WHERE cnpj = '40.806.619/0001-02' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'POSTO DE COMBUSTIVEIS SABIA LTDA' WHERE cnpj = '41.090.635/0001-04' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'POSTO DE COMBUSTIVEIS CONQUISTA LTDA' WHERE cnpj = '41.090.687/0001-80' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'TIG ITIQUIRA IMOVEIS LTDA' WHERE cnpj = '42.021.729/0001-94' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'VIA 050 COMBUSTIVEIS LTDA' WHERE cnpj = '42.239.864/0001-00' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'CONVENIENCIA CASTILHO LTDA' WHERE cnpj = '42.744.984/0001-65' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'POSTO TIGRE 163 LTDA' WHERE cnpj = '42.878.334/0001-02' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'POSTO DE COMBUSTIVEIS DIVISAO LTDA' WHERE cnpj = '43.153.039/0001-51' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'POSTO DE COMBUSTIVEIS CORREA 020 LTDA' WHERE cnpj = '43.288.248/0001-02' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'POSTO DE COMBUSTIVEIS ALVORADA DE PRIMAVERA LTDA' WHERE cnpj = '44.658.468/0001-43' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'ALVIM INVESTIMENTOS E PARTICIPACOES S.A' WHERE cnpj = '45.376.937/0001-02' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'POSTO DE COMBUSTIVEIS RECANTO LTDA' WHERE cnpj = '46.309.350/0001-35' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'TROIS PARTICIPACOES EMPRESARIAIS S.A' WHERE cnpj = '46.740.616/0001-08' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'ARQUEIRO ALVIM COMERCIO DE ALIMENTOS LTDA' WHERE cnpj = '47.014.641/0001-69' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'CAPITAO ALVIM COMERCIO DE ALIMENTOS LTDA' WHERE cnpj = '47.397.598/0001-68' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'TRR SAO ROQUE SIA LTDA' WHERE cnpj = '47.702.635/0001-02' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'RAINHA ALVIM COMERCIO DE ALIMENTOS LTDA' WHERE cnpj = '47.994.803/0001-72' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'TRR SAO ROQUE PARA LTDA' WHERE cnpj = '49.149.733/0001-81' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'POSTO SAO ROQUE SIDNEY LTDA' WHERE cnpj = '50.139.813/0001-35' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'POSTO DE COMBUSTIVEIS ITIQUIRA MATO GROSSO LTDA' WHERE cnpj = '50.534.195/0001-28' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'TRR ITIQUIRA MATO GROSSO LTDA' WHERE cnpj = '50.543.881/0001-65' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'POSTO SAO ROQUE COMODORO LTDA' WHERE cnpj = '50.898.132/0001-50' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'TIG IMOVEIS LTDA' WHERE cnpj = '51.003.821/0001-12' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'CONDESSA ALVIM COMERCIO DE ALIMENTOS LTDA' WHERE cnpj = '52.160.093/0001-15' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'POP VAL COMERCIO DE ALIMENTOS LTDA' WHERE cnpj = '52.193.038/0001-21' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'IMPERATRIZ ALVIM COMERCIO DE ALIMENTOS LTDA' WHERE cnpj = '52.360.597/0001-89' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'POSTO SAO ROQUE ORIZONA LTDA' WHERE cnpj = '52.802.525/0001-44' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'CONVENIENCIA CONQUISTA LTDA' WHERE cnpj = '52.909.016/0001-15' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'POSTO SAO ROQUE BR 080 LTDA' WHERE cnpj = '52.995.302/0001-40' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'POSTO SAO ROQUE RODOANEL DA BARRA LTDA' WHERE cnpj = '53.286.109/0001-01' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'PEROLA PARTICIPACOES S.A' WHERE cnpj = '53.551.098/0001-31' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'RESIDENCIAL PEROLA DO PANTANAL SPE S A' WHERE cnpj = '53.552.304/0001-28' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'EGCP IMOVEIS E PARTICIPACOES LTDA' WHERE cnpj = '54.099.334/0001-93' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'LOJA DE CONVENIENCIA SABIA LTDA' WHERE cnpj = '54.889.094/0001-20' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'LOJA DE CONVENIENCIA 29 LTDA' WHERE cnpj = '54.889.171/0001-42' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'POSTO DE COMBUSTIVEIS CAMINHONEIRO 020 LTDA' WHERE cnpj = '55.031.261/0001-60' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'LOJA DE CONVENIENCIA BR 080 LTDA' WHERE cnpj = '55.444.312/0001-86' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'AUTO POSTO COELHO LTDA' WHERE cnpj = '55.555.254/0001-68' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'CONSTRUTORA SAO ROQUE LTDA' WHERE cnpj = '55.630.256/0001-74' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'POSTO SAO ROQUE CONQUISTA ANAPOLIS LTDA' WHERE cnpj = '55.867.066/0001-75' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'DONZELA ALVIM COMERCIO DE ALIMENTOS LTDA' WHERE cnpj = '55.949.831/0001-04' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'BLEST PARTICIPACOES LTDA' WHERE cnpj = '57.386.870/0001-68' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'POSTO SAO ROQUE BRAZLANDIA LTDA' WHERE cnpj = '57.460.770/0001-34' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'POSTO SAO ROQUE 29 LTDA' WHERE cnpj = '57.710.593/0001-05' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'POSTO SAO ROQUE DA VENDINHA LTDA' WHERE cnpj = '58.114.626/0001-09' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'LOJA DE CONVENIENCIA SAO ROQUE ROTA 050 LTDA' WHERE cnpj = '58.368.644/0001-17' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'RESTAURANTE PRIMAVERA DO LESTE LTDA' WHERE cnpj = '59.306.157/0001-92' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'POSTO SAO ROQUE TEREZOPOLIS LTDA' WHERE cnpj = '59.541.903/0001-22' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'DAMA ALVIM COMERCIO DE ALIMENTOS LTDA' WHERE cnpj = '60.158.898/0001-52' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'POSTO SAO ROQUE PEDRA PRETA LTDA' WHERE cnpj = '60.205.745/0001-19' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'ACADEMIA JP LTDA' WHERE cnpj = '60.718.879/0001-33' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'POSTO SAO ROQUE VILHENA CIDADE LTDA' WHERE cnpj = '61.175.842/0001-79' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'POSTO SAO ROQUE VILHENA RODOVIA LTDA' WHERE cnpj = '61.188.487/0001-72' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'KING ASSESSORIA E CONSULTORIA EMPRESARIAL LTDA' WHERE cnpj = '62.405.047/0001-92' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'POSTO SAO ROQUE TERMINAL LUZIMANGUES LTDA' WHERE cnpj = '63.028.397/0001-40' AND (razao_social = '' OR razao_social IS NULL);
UPDATE public.companies SET razao_social = 'POSTO SAO ROQUE SAPEZAL LTDA' WHERE cnpj = '63.060.253/0001-70' AND (razao_social = '' OR razao_social IS NULL);
COMMIT;
